function Hamburger_Menu() {
  return (
    <svg
      width="16px"
      height="16px"
      viewBox="0 0 32 32"
      enableBackground="new 0 0 32 32"
      id="Editable-line"
      version="1.1"
      xmlSpace="preserve"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <circle
        cx="5"
        cy="6"
        fill="none"
        id="XMLID_303_"
        r="1"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
      />
      <circle
        cx="5"
        cy="16"
        fill="none"
        id="XMLID_305_"
        r="1"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
      />
      <circle
        cx="5"
        cy="26"
        fill="none"
        id="XMLID_304_"
        r="1"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
      />
      <line
        fill="none"
        id="XMLID_29_"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="10"
        x2="28"
        y1="6"
        y2="6"
      />
      <line
        fill="none"
        id="XMLID_30_"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="10"
        x2="28"
        y1="16"
        y2="16"
      />
      <line
        fill="none"
        id="XMLID_31_"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="10"
        x2="28"
        y1="26"
        y2="26"
      />
    </svg>
  );
}

export default Hamburger_Menu;
